name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  dummy:
    name: dummy
    runs-on: ubuntu-latest
    steps:
      - run: sudo update-ca-certificates
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
