name: push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - run: sudo update-ca-certificates
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv tool install bump-my-version
      - run: git config user.email "qrt-bot@queensberry-research.com"
      - run: git config user.name "QRT bot"
      - run: |
          version=$(bump-my-version show current_version)
          git tag -a ${version} HEAD -m ${version}
      - run: git push --tags --force --set-upstream origin
