name: push
"on":
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Tag the latest commit
        uses: dycw/action-tag-commit@latest
